#!/bin/bash

git_sub_function(){
full_path=$(pwd)/${0:2}
echo "Currently in $full_path"
echo "about to do the following command:"
echo "git $1 $2 $3 $4 $5 $6" 
git --git-dir=$full_path/.git --work-tree=$full_path  $1 $2 $3 $4 $5 $6
}
export -f git_sub_function 
find $CWD -mindepth 1 -maxdepth 1 -type d -exec bash -c 'git_sub_function $1 $2 $3 $4 $5 $6 "$7"' {} $1 $2 $3 $4 $5 $6 \;
